version: '3.8'
services:
  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 30
    extra_hosts:
      - "host.docker.internal:host-gateway"

  django:
    build: .
    env_file: .env
    command: python manage.py runserver ${DJANGO_HOST}:${DJANGO_PORT}
    environment:
      - POSTGRES_HOST=host.docker.internal
    privileged: true
    volumes:
      - ./:/panocam
#      - /dev/dri/renderD129:/dev/dri/renderD129
#      - /proc/device-tree/compatible:/proc/device-tree/compatible
#      - /usr/lib/librknnrt.so:/usr/lib/librknnrt.so
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
